apiVersion: v2
name: nextcloud
description: A Helm chart for deploying Nextcloud with PostgreSQL matching Docker deployment without upgrades.
type: application
version: 0.1.0
appVersion: 29.0.0

dependencies:
  - name: nextcloud
    version: 4.6.7
    repository: https://nextcloud.github.io/helm
  - name: postgresql
    version: 15.5.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
