ingressroute:
  enabled: true
  host: "nextcloud.example.com"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
  tls:
    secretName: "nextcloud-tls"

certificate:
  enabled: true
  name: nextcloud-tls
  secretName: nextcloud-tls
  issuer:
    name: "letsencrypt-staging"
    kind: ClusterIssuer
  dnsNames:
    - nextcloud.example.com

service:
  port: 80

nextcloud:
  image:
    tag: 29.0.0

  replicaCount: 1

  nextcloud:
    host: nextcloud.example.com
    username: admin
    password: changeme  # Optional: replace with secret ref
    datadir: /data
    trustedDomains:
      - nextcloud.example.com

  ingress:
    enabled: false

  persistence:
    enabled: false
  nextcloudData:
    enabled: false

  externalDatabase:
    enabled: false

  redis:
    enabled: false

  strategy:
    type: Recreate

postgresql:
  enabled: false

redis:
  enabled: false

mariadb:
  enabled: false

collabora:
  enabled: false
